services:
  - type: web
    name: stylist-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        sync: false
